export const GET_TEMP_DIR = "GET_TEMP_DIR";
export const GET_CHARACTOR_INFOS = "GET_CHARACTOR_INFOS";
export const GET_OSS_LICENSES = "GET_OSS_LICENSES";
export const SHOW_SAVE_DIALOG = "SHOW_SAVE_DIALOG";
export const SHOW_OPEN_DIRECOTRY_DIALOG = "SHOW_OPEN_DIRECOTRY_DIALOG";
export const SHOW_IMPORT_FILE_DIALOG = "SHOW_IMPORT_FILE_DIALOG";
export const CREATE_HELP_WINDOW = "CREATE_HELP_WINDOW";
export const CREATE_TEXT_EDIT_CONTEXT_MENU = "CREATE_TEXT_EDIT_CONTEXT_MENU";
