export const GENERATE_AND_SAVE_ALL_AUDIO = "GENERATE_AND_SAVE_ALL_AUDIO";
export const IMPORT_FROM_FILE = "IMPORT_FROM_FILE";
export const SAVE_PROJECT_FILE = "SAVE_PROJECT_FILE";
export const LOAD_PROJECT_FILE = "LOAD_PROJECT_FILE";
