export const GET_APP_INFOS = "GET_APP_INFOS";
export const GET_TEMP_DIR = "GET_TEMP_DIR";
export const GET_CHARACTOR_INFOS = "GET_CHARACTOR_INFOS";
export const GET_OSS_LICENSES = "GET_OSS_LICENSES";
export const GET_UPDATE_INFOS = "GET_UPDATE_INFOS";
export const SHOW_AUDIO_SAVE_DIALOG = "SHOW_AUDIO_SAVE_DIALOG";
export const SHOW_OPEN_DIRECOTRY_DIALOG = "SHOW_OPEN_DIRECOTRY_DIALOG";
export const SHOW_IMPORT_FILE_DIALOG = "SHOW_IMPORT_FILE_DIALOG";
export const CREATE_HELP_WINDOW = "CREATE_HELP_WINDOW";
export const OPEN_TEXT_EDIT_CONTEXT_MENU = "OPEN_TEXT_EDIT_CONTEXT_MENU";
export const SHOW_PROJECT_SAVE_DIALOG = "SHOW_PROJECT_SAVE_DIALOG";
export const SHOW_PROJECT_LOAD_DIALOG = "SHOW_PROJECT_LOAD_DIALOG";
export const SHOW_CONFIRM_DIALOG = "SHOW_CONFIRM_DIALOG";

export const GENERATE_AND_SAVE_ALL_AUDIO = "GENERATE_AND_SAVE_ALL_AUDIO";
export const IMPORT_FROM_FILE = "IMPORT_FROM_FILE";
export const SAVE_PROJECT_FILE = "SAVE_PROJECT_FILE";
export const LOAD_PROJECT_FILE = "LOAD_PROJECT_FILE";
