name: "Setup environment"
description: |
  依存関係のインストールなどを行う。
runs:
  using: "composite"
  steps:
    - name: Setup variable
      shell: bash
      run: |
        echo "ELECTRON_CACHE=${{ runner.temp }}/electron-cache" >> $GITHUB_ENV
        echo "ELECTRON_BUILDER_CACHE=${{ runner.temp }}/electron-builder-cache" >> $GITHUB_ENV
        echo "cache-version=1" >> $GITHUB_ENV

    - name: Setup pnpm
      uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4.3.0

    - name: Setup Node
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
      with:
        node-version-file: ".node-version"
        cache: "pnpm"

    - name: Cache Electron
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      with:
        path: ${{ env.ELECTRON_CACHE }}
        key: ${{ env.cache-version }}-${{ runner.os }}--electron-cache-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ env.cache-version }}-${{ runner.os }}--electron-cache-

    - name: Cache Electron-Builder
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      with:
        path: ${{ env.ELECTRON_BUILDER_CACHE }}
        key: ${{ env.cache-version }}-${{ runner.os }}--electron-builder-cache-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ env.cache-version }}-${{ runner.os }}--electron-builder-cache-

    - shell: bash
      run: pnpm install --frozen-lockfile
