/* tslint:disable */
/* eslint-disable */
/**
 * VOICEVOX ENGINE
 * VOICEVOXの音声合成エンジンです。
 *
 * The version of the OpenAPI document: 0.12.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Speaker,
    SpeakerFromJSON,
    SpeakerFromJSONTyped,
    SpeakerToJSON,
    SpeakerInfo,
    SpeakerInfoFromJSON,
    SpeakerInfoFromJSONTyped,
    SpeakerInfoToJSON,
} from './';

/**
 * ダウンロードモデル情報話者
 * @export
 * @interface DownloadableModel
 */
export interface DownloadableModel {
    /**
     *
     * @type {string}
     * @memberof DownloadableModel
     */
    downloadPath: string;
    /**
     *
     * @type {string}
     * @memberof DownloadableModel
     */
    volume: string;
    /**
     *
     * @type {Speaker}
     * @memberof DownloadableModel
     */
    speaker: Speaker;
    /**
     *
     * @type {SpeakerInfo}
     * @memberof DownloadableModel
     */
    speakerInfo: SpeakerInfo;
}

export function DownloadableModelFromJSON(json: any): DownloadableModel {
    return DownloadableModelFromJSONTyped(json, false);
}

export function DownloadableModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): DownloadableModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }

    return {

        'downloadPath': json['download_path'],
        'volume': json['volume'],
        'speaker': SpeakerFromJSON(json['speaker']),
        'speakerInfo': SpeakerInfoFromJSON(json['speaker_info']),
    };
}

export function DownloadableModelToJSON(value?: DownloadableModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'download_path': value.downloadPath,
        'volume': value.volume,
        'speaker': SpeakerToJSON(value.speaker),
        'speakerInfo': SpeakerInfoToJSON(value.speakerInfo),
    };
}
