/* tslint:disable */
/* eslint-disable */
/**
 * VOICEVOX ENGINE
 * VOICEVOXの音声合成エンジンです。
 *
 * The version of the OpenAPI document: 0.12.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    DownloadableModel,
    DownloadableModelFromJSON,
    DownloadableModelFromJSONTyped,
    DownloadableModelToJSON,
} from './';

/**
 * ダウンロード話者情報
 * @export
 * @interface DownloadInfo
 */
export interface DownloadInfo {
    /**
     *
     * @type {DownloadableModel}
     * @memberof DownloadInfo
     */
    downloadableModel: DownloadableModel;
    /**
     *
     * @type {string}
     * @memberof DownloadInfo
     */
    currentVersion: string;
    /**
     *
     * @type {boolean}
     * @memberof DownloadInfo
     */
    characterExists: boolean;
    /**
     *
     * @type {boolean}
     * @memberof DownloadInfo
     */
    latestModelExists: boolean;
}

export function DownloadInfoFromJSON(json: any): DownloadInfo {
    return DownloadInfoFromJSONTyped(json, false);
}

export function DownloadInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): DownloadInfo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'downloadableModel': DownloadableModelFromJSON(json['downloadable_model']),
        'currentVersion': json['current_version'],
        'characterExists': json['character_exists'],
        'latestModelExists': json['latest_model_exists'],
    };
}

export function DownloadInfoToJSON(value?: DownloadInfo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'downloadable_model': DownloadableModelToJSON(value.downloadableModel),
        'current_version': value.currentVersion,
        'character_exists': value.characterExists,
        'latest_model_exists': value.latestModelExists,
    };
}
