/* tslint:disable */
/* eslint-disable */
/**
 * VOICEVOX Engine
 * VOICEVOXの音声合成エンジンです。
 *
 * The version of the OpenAPI document: 0.15.0-preview.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Speaker,
    SpeakerFromJSON,
    SpeakerFromJSONTyped,
    SpeakerToJSON,
    SpeakerInfo,
    SpeakerInfoFromJSON,
    SpeakerInfoFromJSONTyped,
    SpeakerInfoToJSON,
} from './';

/**
 * 音声ライブラリに含まれる話者の情報
 * @export
 * @interface LibrarySpeaker
 */
export interface LibrarySpeaker {
    /**
     * 
     * @type {Speaker}
     * @memberof LibrarySpeaker
     */
    speaker: Speaker | null;
    /**
     * 
     * @type {SpeakerInfo}
     * @memberof LibrarySpeaker
     */
    speakerInfo: SpeakerInfo | null;
}

export function LibrarySpeakerFromJSON(json: any): LibrarySpeaker {
    return LibrarySpeakerFromJSONTyped(json, false);
}

export function LibrarySpeakerFromJSONTyped(json: any, ignoreDiscriminator: boolean): LibrarySpeaker {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'speaker': SpeakerFromJSON(json['speaker']),
        'speakerInfo': SpeakerInfoFromJSON(json['speaker_info']),
    };
}

export function LibrarySpeakerToJSON(value?: LibrarySpeaker | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'speaker': SpeakerToJSON(value.speaker),
        'speaker_info': SpeakerInfoToJSON(value.speakerInfo),
    };
}

