/* tslint:disable */
/* eslint-disable */
/**
 * VOICEVOX Engine
 * VOICEVOXの音声合成エンジンです。
 *
 * The version of the OpenAPI document: 0.15.0-projects.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 周期的なデータの情報
 * @export
 * @interface PeriodicData
 */
export interface PeriodicData {
    /**
     * 
     * @type {number}
     * @memberof PeriodicData
     */
    rate: number;
    /**
     * 
     * @type {Array<number>}
     * @memberof PeriodicData
     */
    data: Array<number>;
}

/**
 * Check if a given object implements the PeriodicData interface.
 */
export function instanceOfPeriodicData(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "rate" in value;
    isInstance = isInstance && "data" in value;

    return isInstance;
}

export function PeriodicDataFromJSON(json: any): PeriodicData {
    return PeriodicDataFromJSONTyped(json, false);
}

export function PeriodicDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): PeriodicData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'rate': json['rate'],
        'data': json['data'],
    };
}

export function PeriodicDataToJSON(value?: PeriodicData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'rate': value.rate,
        'data': value.data,
    };
}

