/* tslint:disable */
/* eslint-disable */
/**
 * DUMMY Engine
 * DUMMY の音声合成エンジンです。
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * プリセット情報
 * @export
 * @interface Preset
 */
export interface Preset {
    /**
     * プリセットID
     * @type {number}
     * @memberof Preset
     */
    id: number;
    /**
     * プリセット名
     * @type {string}
     * @memberof Preset
     */
    name: string;
    /**
     * キャラクターのUUID
     * @type {string}
     * @memberof Preset
     */
    speakerUuid: string;
    /**
     * スタイルID
     * @type {number}
     * @memberof Preset
     */
    styleId: number;
    /**
     * 全体の話速
     * @type {number}
     * @memberof Preset
     */
    speedScale: number;
    /**
     * 全体の音高
     * @type {number}
     * @memberof Preset
     */
    pitchScale: number;
    /**
     * 全体の抑揚
     * @type {number}
     * @memberof Preset
     */
    intonationScale: number;
    /**
     * 全体の音量
     * @type {number}
     * @memberof Preset
     */
    volumeScale: number;
    /**
     * 音声の前の無音時間
     * @type {number}
     * @memberof Preset
     */
    prePhonemeLength: number;
    /**
     * 音声の後の無音時間
     * @type {number}
     * @memberof Preset
     */
    postPhonemeLength: number;
    /**
     * 句読点などの無音時間
     * @type {number}
     * @memberof Preset
     */
    pauseLength?: number;
    /**
     * 句読点などの無音時間（倍率）
     * @type {number}
     * @memberof Preset
     */
    pauseLengthScale?: number;
}

/**
 * Check if a given object implements the Preset interface.
 */
export function instanceOfPreset(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "speakerUuid" in value;
    isInstance = isInstance && "styleId" in value;
    isInstance = isInstance && "speedScale" in value;
    isInstance = isInstance && "pitchScale" in value;
    isInstance = isInstance && "intonationScale" in value;
    isInstance = isInstance && "volumeScale" in value;
    isInstance = isInstance && "prePhonemeLength" in value;
    isInstance = isInstance && "postPhonemeLength" in value;

    return isInstance;
}

export function PresetFromJSON(json: any): Preset {
    return PresetFromJSONTyped(json, false);
}

export function PresetFromJSONTyped(json: any, ignoreDiscriminator: boolean): Preset {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'speakerUuid': json['speaker_uuid'],
        'styleId': json['style_id'],
        'speedScale': json['speedScale'],
        'pitchScale': json['pitchScale'],
        'intonationScale': json['intonationScale'],
        'volumeScale': json['volumeScale'],
        'prePhonemeLength': json['prePhonemeLength'],
        'postPhonemeLength': json['postPhonemeLength'],
        'pauseLength': !exists(json, 'pauseLength') ? undefined : json['pauseLength'],
        'pauseLengthScale': !exists(json, 'pauseLengthScale') ? undefined : json['pauseLengthScale'],
    };
}

export function PresetToJSON(value?: Preset | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'speaker_uuid': value.speakerUuid,
        'style_id': value.styleId,
        'speedScale': value.speedScale,
        'pitchScale': value.pitchScale,
        'intonationScale': value.intonationScale,
        'volumeScale': value.volumeScale,
        'prePhonemeLength': value.prePhonemeLength,
        'postPhonemeLength': value.postPhonemeLength,
        'pauseLength': value.pauseLength,
        'pauseLengthScale': value.pauseLengthScale,
    };
}

