/* tslint:disable */
/* eslint-disable */
/**
 * VOICEVOX ENGINE OSS
 * VOICEVOX OSS の音声合成エンジンです。
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 乱数のシード設定。
 * @export
 * @interface Seeding
 */
export interface Seeding {
    /**
     * 乱数シード値。
     * @type {number}
     * @memberof Seeding
     */
    seed: number;
    /**
     * 乱数列のオフセット。シード値から生成される乱数列を先頭から何フレーム分ずらして使うかを表す。
     * @type {number}
     * @memberof Seeding
     */
    offset?: number;
}

/**
 * Check if a given object implements the Seeding interface.
 */
export function instanceOfSeeding(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "seed" in value;

    return isInstance;
}

export function SeedingFromJSON(json: any): Seeding {
    return SeedingFromJSONTyped(json, false);
}

export function SeedingFromJSONTyped(json: any, ignoreDiscriminator: boolean): Seeding {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'seed': json['seed'],
        'offset': !exists(json, 'offset') ? undefined : json['offset'],
    };
}

export function SeedingToJSON(value?: Seeding | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'seed': value.seed,
        'offset': value.offset,
    };
}

