/* tslint:disable */
/* eslint-disable */
/**
 * VOICEVOX Engine
 * VOICEVOXの音声合成エンジンです。
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * An enumeration.
 * @export
 * @enum {string}
 */
export enum SpeakerSupportPermittedSynthesisMorphing {
    All = 'ALL',
    SelfOnly = 'SELF_ONLY',
    Nothing = 'NOTHING'
}

export function SpeakerSupportPermittedSynthesisMorphingFromJSON(json: any): SpeakerSupportPermittedSynthesisMorphing {
    return SpeakerSupportPermittedSynthesisMorphingFromJSONTyped(json, false);
}

export function SpeakerSupportPermittedSynthesisMorphingFromJSONTyped(json: any, ignoreDiscriminator: boolean): SpeakerSupportPermittedSynthesisMorphing {
    return json as SpeakerSupportPermittedSynthesisMorphing;
}

export function SpeakerSupportPermittedSynthesisMorphingToJSON(value?: SpeakerSupportPermittedSynthesisMorphing | null): any {
    return value as any;
}

