/* tslint:disable */
/* eslint-disable */
/**
 * VOICEVOX Engine
 * VOICEVOXの音声合成エンジンです。
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SpeakerOptimalPitchRangeItem
 */
export interface SpeakerOptimalPitchRangeItem {
    /**
     * 
     * @type {number}
     * @memberof SpeakerOptimalPitchRangeItem
     */
    styleId: number;
    /**
     * 
     * @type {number}
     * @memberof SpeakerOptimalPitchRangeItem
     */
    high: number;
    /**
     * 
     * @type {number}
     * @memberof SpeakerOptimalPitchRangeItem
     */
    low: number;
}

/**
 * Check if a given object implements the SpeakerOptimalPitchRangeItem interface.
 */
export function instanceOfSpeakerOptimalPitchRangeItem(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "styleId" in value;
    isInstance = isInstance && "high" in value;
    isInstance = isInstance && "low" in value;

    return isInstance;
}

export function SpeakerOptimalPitchRangeItemFromJSON(json: any): SpeakerOptimalPitchRangeItem {
    return SpeakerOptimalPitchRangeItemFromJSONTyped(json, false);
}

export function SpeakerOptimalPitchRangeItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): SpeakerOptimalPitchRangeItem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'styleId': json['style_id'],
        'high': json['high'],
        'low': json['low'],
    };
}

export function SpeakerOptimalPitchRangeItemToJSON(value?: SpeakerOptimalPitchRangeItem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'style_id': value.styleId,
        'high': value.high,
        'low': value.low,
    };
}

