/* tslint:disable */
/* eslint-disable */
/**
 * VOICEVOX ENGINE
 * VOICEVOXの音声合成エンジンです。
 *
 * The version of the OpenAPI document: 0.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 話者の追加情報
 * @export
 * @interface SpeakerInfo
 */
export interface SpeakerInfo {
    /**
     * 
     * @type {string}
     * @memberof SpeakerInfo
     */
    policy: string;
    /**
     * 
     * @type {string}
     * @memberof SpeakerInfo
     */
    portrait: string;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof SpeakerInfo
     */
    icons: { [key: string]: string; };
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof SpeakerInfo
     */
    voiceSamples: { [key: string]: string; };
}

export function SpeakerInfoFromJSON(json: any): SpeakerInfo {
    return SpeakerInfoFromJSONTyped(json, false);
}

export function SpeakerInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SpeakerInfo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'policy': json['policy'],
        'portrait': json['portrait'],
        'icons': json['icons'],
        'voiceSamples': json['voice_samples'],
    };
}

export function SpeakerInfoToJSON(value?: SpeakerInfo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'policy': value.policy,
        'portrait': value.portrait,
        'icons': value.icons,
        'voice_samples': value.voiceSamples,
    };
}


