/* tslint:disable */
/* eslint-disable */
/**
 * VOICEVOX Engine
 * VOICEVOXの音声合成エンジンです。
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StylePitchRange
 */
export interface StylePitchRange {
    /**
     * 
     * @type {number}
     * @memberof StylePitchRange
     */
    low: number;
    /**
     * 
     * @type {number}
     * @memberof StylePitchRange
     */
    high: number;
}

/**
 * Check if a given object implements the StylePitchRange interface.
 */
export function instanceOfStylePitchRange(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "low" in value;
    isInstance = isInstance && "high" in value;

    return isInstance;
}

export function StylePitchRangeFromJSON(json: any): StylePitchRange {
    return StylePitchRangeFromJSONTyped(json, false);
}

export function StylePitchRangeFromJSONTyped(json: any, ignoreDiscriminator: boolean): StylePitchRange {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'low': json['low'],
        'high': json['high'],
    };
}

export function StylePitchRangeToJSON(value?: StylePitchRange | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'low': value.low,
        'high': value.high,
    };
}

