/* tslint:disable */
/* eslint-disable */
/**
 * VOICEVOX ENGINE
 * VOICEVOXの音声合成エンジンです。
 *
 * The version of the OpenAPI document: 0.14.0-preview.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * エンジンが持つ機能の一覧
 * @export
 * @interface SupportedFeatures
 */
export interface SupportedFeatures {
    /**
     * 
     * @type {boolean}
     * @memberof SupportedFeatures
     */
    adjustMoraPitch: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof SupportedFeatures
     */
    adjustPhonemeLength: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof SupportedFeatures
     */
    adjustSpeedScale: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof SupportedFeatures
     */
    adjustPitchScale: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof SupportedFeatures
     */
    adjustIntonationScale: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof SupportedFeatures
     */
    adjustVolumeScale: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof SupportedFeatures
     */
    interrogativeUpspeak: boolean;
}

export function SupportedFeaturesFromJSON(json: any): SupportedFeatures {
    return SupportedFeaturesFromJSONTyped(json, false);
}

export function SupportedFeaturesFromJSONTyped(json: any, ignoreDiscriminator: boolean): SupportedFeatures {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'adjustMoraPitch': json['adjust_mora_pitch'],
        'adjustPhonemeLength': json['adjust_phoneme_length'],
        'adjustSpeedScale': json['adjust_speed_scale'],
        'adjustPitchScale': json['adjust_pitch_scale'],
        'adjustIntonationScale': json['adjust_intonation_scale'],
        'adjustVolumeScale': json['adjust_volume_scale'],
        'interrogativeUpspeak': json['interrogative_upspeak'],
    };
}

export function SupportedFeaturesToJSON(value?: SupportedFeatures | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'adjust_mora_pitch': value.adjustMoraPitch,
        'adjust_phoneme_length': value.adjustPhonemeLength,
        'adjust_speed_scale': value.adjustSpeedScale,
        'adjust_pitch_scale': value.adjustPitchScale,
        'adjust_intonation_scale': value.adjustIntonationScale,
        'adjust_volume_scale': value.adjustVolumeScale,
        'interrogative_upspeak': value.interrogativeUpspeak,
    };
}

