name: Bump the Homebrew cask on release

on:
  release:
    types: [ published ]

jobs:
  bump-casks:
    runs-on: macos-latest
    steps:
      - uses: macauley/action-homebrew-bump-cask@v1.0.0
        with:
          # Required, custom GitHub access token with only the 'public_repo' scope enabled
          token: ${{ secrets.BUMP_CASK_TOKEN }}
          tap: VOICEVOX/voicevox
          cask: voicevox
          livecheck: true
          dryrun: false
